description: 
pack: aws
enabled: true
entry_point: run.py
name: config_put_evaluations
runner_type: python-script
parameters:
  action:
    default: put_evaluations
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ResultToken:
    type: string
    description: "An encrypted token that associates an evaluation with an AWS Config rule. Identifies the rule and the event that triggered the evaluation"
    required: true
  Evaluations:
    type: array
    description: "The assessments that the AWS Lambda function performs. Each evaluation identifies an AWS resource and indicates whether it complies with the AWS Config rule that invokes the AWS Lambda function."
  TestMode:
    type: boolean
    description: "Use this parameter to specify a test run for PutEvaluations. You can verify whether your AWS Lambda function will deliver evaluation results to AWS Config. No updates occur to your existing evaluations, and evaluation results are not sent to AWS Config.  When TestMode is true, PutEvaluations doesn't require a valid value for the ResultToken parameter, but the value cannot be null. "