description: 
pack: aws
enabled: true
entry_point: run.py
name: lambda_get_account_settings
runner_type: run-python
parameters:
  action:
    default: get_account_settings
    immutable: true
    type: string
  cls:
    default: lambda
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string